### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by RickCarlino** [pzavolinsky/ts-unused-exports#1]
# Steps Taken

```
npm install -g ts-unused-exports
ts-unused-exports tsconfig.json
```

Running Node `v4.5.0` on Linux Mint. Got the following error:

```
$ ts-unused-exports tsconfig.json 

/usr/lib/node_modules/ts-unused-exports/lib/parser.js:141
        .filter(function (p) { return p.indexOf('.d.') == -1; })
        ^

TypeError: Cannot read property 'filter' of undefined
    at Object.exports.default (/usr/lib/node_modules/ts-unused-exports/lib/parser.js:141:9)
    at Object.exports.default (/usr/lib/node_modules/ts-unused-exports/lib/app.js:8:47)
    at Object.<anonymous> (/usr/lib/node_modules/ts-unused-exports/lib/cli.js:9:29)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/ts-unused-exports/bin/ts-unused-exports:2:1)

```

Full source code of the project I ran it on can be found [here](https://github.com/FarmBot/farmbot-web-frontend).

This looks like a great idea. I really hope I can get it working! Thanks for the help.

**Comment by RickCarlino** [comment]
I see the issue now- my `tsconfig.json` does not have a `files` property, so the analyzer is trying to iterate over `undefined`. I can temporarily add a `files` attribute to my `tsconfig.json` to run the analysis.

**Comment by pzavolinsky** [comment]
Hi @RickCarlino , thanks for reporting this, I should add a null check to the CLI and show something more helpful than `Cannot read property 'filter' of undefined`.

**Comment by pzavolinsky** [comment]
Hi @RickCarlino I just pushed version `1.0.2.` that allows you to explicitly pass the files you want to check in the command line so that you can avoid generating the `files` key in your `tsconfig.json`.

The example would be:

```shell
./bin/ts-unused-exports example/tsconfig.json $(cd example; find -name '*.ts')
```

Note that you need to `cd` into the directory that contains the `tsconfig.json` in the sub-shell. This is because the files must be relative to the path of the `tsconfig.json`.

Hope this helps!

Cheers!
