### ISSUE TITLE
False ENOENT "no such file or directory" error

### ISSUE THREAD

**Issue by OliverJAsh** [pzavolinsky/ts-unused-exports#8]
Given:

```
❯ yarn list ts-unused-exports
yarn list v0.24.5
└─ ts-unused-exports@2.0.3
```

``` ts
// index.ts
import { bar } from './helpers/index';
```

``` ts
helpers/index.ts
export const foo = 'bar';
export const bar = 'bar';
```

When I run `ts-unused-exports tsconfig.json ./src/index.ts`, I get this error:

```
❯ ts-unused-exports tsconfig.json ./src/index.ts
{ Error: ENOENT: no such file or directory, open '/Users/OliverJAsh/Development/twitter-paper/src/helpers.ts'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at parseFile (/Users/OliverJAsh/Development/twitter-paper/node_modules/ts-unused-exports/lib/parser.js:148:66)
    at /Users/OliverJAsh/Development/twitter-paper/node_modules/ts-unused-exports/lib/parser.js:154:39
    at Array.map (native)
    at parsePaths (/Users/OliverJAsh/Development/twitter-paper/node_modules/ts-unused-exports/lib/parser.js:154:10)
    at parsePaths (/Users/OliverJAsh/Development/twitter-paper/node_modules/ts-unused-exports/lib/parser.js:160:11)
    at Object.exports.default (/Users/OliverJAsh/Development/twitter-paper/node_modules/ts-unused-exports/lib/parser.js:165:12)
    at Object.exports.default (/Users/OliverJAsh/Development/twitter-paper/node_modules/ts-unused-exports/lib/app.js:28:47)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/OliverJAsh/Development/twitter-paper/src/helpers.ts' }
```

**Comment by danvk** [comment]
The problem is that it's looking for `src/helpers.ts` and not considering that the code might be in `src/helpers/index.ts`. I'm running into this, too.

**Comment by pzavolinsky** [comment]
Hi guys, sorry for the delay looking into this. I've just pushed `2.0.4` that should fix these issues (`index.ts` and `index.tsx`).

Please let me know if this is the case and we can close the issue.

Cheers!

**Comment by OliverJAsh** [comment]
Yup it's fixed!
